In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
    return x * (1-x)

In [3]:
training_inputs = np.array([[0,0,1], [1,1,1], [1,0,1], [0,1,1]])
training_outputs = np.array([[0,1,1,0]]).T

In [5]:
np.random.seed(1)
synaptic_weights = 2 * np.random.random((3,1))-1

print('Random starting weights : ')
print(synaptic_weights)

Random starting weights : 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [7]:
for i in range(100000):
    input_layer = training_inputs
    
    outputs = sigmoid(np.dot(input_layer, synaptic_weights))
    
    error = training_outputs - outputs
    
    adjustments = error * sigmoid_derivative(outputs)
    
    synaptic_weights += np.dot(input_layer.T, adjustments)
    
print('Synaptic weights after training :')
print(synaptic_weights)
    
print('Output after training :')
print(outputs)

Synaptic weights after training :
[[12.00871069]
 [-0.20441159]
 [-5.80028725]]
Output after training :
[[0.00301757]
 [0.99753724]
 [0.99799162]
 [0.00246107]]
